/* ===================================================================
    Facebook/Google Tracking
====================================================================== */

$.fn.isInViewport = function() {
    var elementTop = $(this).offset().top;
    var elementBottom = elementTop + $(this).outerHeight();
    var viewportTop = $(window).scrollTop();
    var viewportBottom = viewportTop + $(window).height();
    return elementBottom > viewportTop && elementTop < viewportBottom;
};

function track_event(name, category, value) {
    
    // Track Facebook
    fbq('trackCustom', name, {
        event_category: category,
        event_val: value 
    });
    
    // Track Google
    ga('send', {
        hitType: 'event',
        eventCategory: category,
        eventAction: name,
        eventLabel: value
    });
    
}

jQuery(function($) {    
    
    // Scroll Depth Tracking 
    var quarter = half = threeQuarter = whole = false;
    
    $(window).scroll(function() {
        
        var s = $(window).scrollTop(),
            d = $(document).height(),
            c = $(window).height();

        var scrollPercent = (s / (d-c)) * 100;
        
        if ( scrollPercent == 100 && whole === false) {
            track_event('scroll', 'scroll-depth', '100');
            whole = true;
        } else if (scrollPercent >= 75 && threeQuarter === false) {
            track_event('scroll', 'scroll-depth', '75');
            threeQuarter = true;
        } else if (scrollPercent >= 50 && half === false) {
            track_event('scroll', 'scroll-depth', '50');
            half = true;
        } else if (scrollPercent >= 25 && quarter === false) {
            track_event('scroll', 'scroll-depth', '25');
            quarter = true;
        }
        
    });
    
    // Stopgap solution for events on registration links @todo
    $('.register-episode-1').on('click', function() {
        track_event('register', 'leadership-series', 'top');
    });
    
    $('.register-episode-1a').on('click', function() {
        track_event('register', 'leadership-series', 'bottom');
    });
    
    $('.sa-track').on('click', function() {
        var data = $(this).attr('data-track');
        track_event(data, 'sa', 'click');
    });
    
    // Global Tracking for Buttons generated by shortcodes
    $('.tracking-button').on('click', function() {
        var category = $(this).attr('data-event-category'),
            name = $(this).attr('data-event-name'),
            value = $(this).attr('data-event-value');
            
        track_event(name, category, value);
    });
    
    // Track submitted forms
    $(document).bind('gform_confirmation_loaded', function(event, formId){
        track_event('submit', 'form', formId);
    });
    
    // Vimeo Tracking Code
    var iframes = document.querySelectorAll('iframe');
    
    iframes.forEach(function(iframe, i) {
        if (iframe.getAttribute('src').includes('vimeo')) {
            var player = new Vimeo.Player(iframe);
            var quarter = half = threeQuarter = ninety = false;
            var videoTitle = '';
            var inView = false;
            
            $(window).on('load scroll', function() {
                if ($(iframe).isInViewport() && inView == false) {
                    track_event('in_view', 'video', videoTitle);
                    inView = true;
                }
            });
            
            player.getVideoTitle().then(function(title) {
                videoTitle = title;
            });
            
            player.on('play', function() {
                track_event('play', 'video', videoTitle);
            });
            
            player.on('pause', function() {
                track_event('pause', 'video', videoTitle);
            });
            
            player.on('timeupdate', function(e) {
                if (e.percent >= 0.25 && quarter == false) {
                    track_event('progress - 25%', 'video', videoTitle);
                    quarter = true;
                } else if (e.percent >= 0.50 && half == false) {
                    track_event('progress - 50%', 'video', videoTitle);
                    half = true;
                } else if (e.percent >= 0.75 && threeQuarter == false) {
                    track_event('progress - 75%', 'video', videoTitle);
                    threeQuarter = true;
                } else if (e.percent >= 0.90 && ninety == false) {
                    track_event('progress - 90%', 'video', videoTitle);
                    ninety = true;
                }
                
            });
            
            player.on('seeked', function(e) {
                var percent = e.percent * 100;
                track_event('seeked to' + Math.round(percent) + '%', 'video', videoTitle);
            });
            
            player.on('ended', function(e) {
                track_event('finished', 'video', videoTitle);
            });
        }
    });
});
